# Generated by Django 4.2.3 on 2023-08-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_category_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='descripiion',
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
