# Generated by Django 4.2.3 on 2023-08-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pix',
            field=models.ImageField(default='profile.jpg', upload_to='Profile'),
        ),
    ]
